/**
 * Map{字段类型: 相应可执行操作}
 * 0-字符串类型，1-数字类型,2-时间类型 ,3-小数类型，4-布尔类型
 */
import {translate as t} from '@/locales';

export const FUNCTION_MAP = {
    // 0-字符串类型
    0: [
        {id: 'equal', name: t('analysis.equal')},
        {id: 'notEqual', name: t('analysis.unEqual')},
        {id: 'contain', name: t('analysis.contains')},
        {id: 'notContain', name: t('analysis.notContain')},
        {id: 'isSet', name: t('analysis.value')},
        {id: 'notSet', name: t('analysis.none')},
        {id: 'rlike', name: t('analysis.regexMatch')},
        {id: 'notRlike', name: t('analysis.unMatch')},
    ],
    // 1-数字类型
    1: [
        {id: 'equal', name: t('analysis.equal')},
        {id: 'notEqual', name: t('analysis.unEqual')},
        {id: 'greater', name: t('analysis.moreThan')},
        {id: 'less', name: t('analysis.lessThan')},
        {id: 'greaterEqual', name: t('analysis.moreEqual')},
        {id: 'lessEqual', name: t('analysis.lessEqual')},
        {id: 'between', name: t('analysis.range')},
        {id: 'notBetween', name: t('analysis.notRange')},
        {id: 'isSet', name: t('analysis.value')},
        {id: 'notSet', name: t('analysis.none')},
    ],
    // 2-时间类型
    2: [
        {id: 'collect', name: t('analysis.summarize')},
        {id: 'between', name: t('analysis.absoluteTime')},
        {id: 'relative', name: t('analysis.relativeTime')},
        {id: 'relativeBetween', name: t('analysis.relativeTimeRange')},
        {id: 'relativeEventTime', name: t('analysis.relativeEventTime')},
        {id: 'isSet', name: t('analysis.value')},
        {id: 'notSet', name: t('analysis.none')},
    ],
    // 3-小数类型
    3: [
        {id: 'equal', name: t('analysis.equal')},
        {id: 'notEqual', name: t('analysis.unEqual')},
        {id: 'greater', name: t('analysis.moreThan')},
        {id: 'less', name: t('analysis.lessThan')},
        {id: 'greaterEqual', name: t('analysis.moreEqual')},
        {id: 'lessEqual', name: t('analysis.lessEqual')},
        {id: 'between', name: t('analysis.range')},
        {id: 'notBetween', name: t('analysis.notRange')},
        {id: 'isSet', name: t('analysis.value')},
        {id: 'notSet', name: t('analysis.none')},
    ],
    // 4-布尔类型
    4: [
        {id: 'isTrue', name: t('analysis.true')},
        {id: 'isFalse', name: t('analysis.false')},
    ]
};

// 当function为collect时
export const COLLECT_MAP = {
    'minute': [
        t('analysis.minute0'),
        t('analysis.minute1'),
        t('analysis.minute2'),
        t('analysis.minute3'),
        t('analysis.minute4'),
        t('analysis.minute5'),
        t('analysis.minute6'),
        t('analysis.minute7'),
        t('analysis.minute8'),
        t('analysis.minute9'),
        t('analysis.minute10'),
        t('analysis.minute11'),
        t('analysis.minute12'),
        t('analysis.minute13'),
        t('analysis.minute14'),
        t('analysis.minute15'),
        t('analysis.minute16'),
        t('analysis.minute17'),
        t('analysis.minute18'),
        t('analysis.minute19'),
        t('analysis.minute20'),
        t('analysis.minute21'),
        t('analysis.minute22'),
        t('analysis.minute23'),
        t('analysis.minute24'),
        t('analysis.minute25'),
        t('analysis.minute26'),
        t('analysis.minute27'),
        t('analysis.minute28'),
        t('analysis.minute29'),
        t('analysis.minute30'),
        t('analysis.minute31'),
        t('analysis.minute32'),
        t('analysis.minute33'),
        t('analysis.minute34'),
        t('analysis.minute35'),
        t('analysis.minute36'),
        t('analysis.minute37'),
        t('analysis.minute38'),
        t('analysis.minute39'),
        t('analysis.minute40'),
        t('analysis.minute41'),
        t('analysis.minute42'),
        t('analysis.minute43'),
        t('analysis.minute44'),
        t('analysis.minute45'),
        t('analysis.minute46'),
        t('analysis.minute47'),
        t('analysis.minute48'),
        t('analysis.minute49'),
        t('analysis.minute50'),
        t('analysis.minute51'),
        t('analysis.minute52'),
        t('analysis.minute53'),
        t('analysis.minute54'),
        t('analysis.minute55'),
        t('analysis.minute56'),
        t('analysis.minute57'),
        t('analysis.minute58'),
        t('analysis.minute59'),
    ],
    'hour': [
        t('analysis.hour0'),
        t('analysis.hour1'),
        t('analysis.hour2'),
        t('analysis.hour3'),
        t('analysis.hour4'),
        t('analysis.hour5'),
        t('analysis.hour6'),
        t('analysis.hour7'),
        t('analysis.hour8'),
        t('analysis.hour9'),
        t('analysis.hour10'),
        t('analysis.hour11'),
        t('analysis.hour12'),
        t('analysis.hour13'),
        t('analysis.hour14'),
        t('analysis.hour15'),
        t('analysis.hour16'),
        t('analysis.hour17'),
        t('analysis.hour18'),
        t('analysis.hour19'),
        t('analysis.hour20'),
        t('analysis.hour21'),
        t('analysis.hour22'),
        t('analysis.hour23'),
    ],
    'week': [
        t('analysis.monday'),
        t('analysis.tuesday'),
        t('analysis.wednesday'),
        t('analysis.thursday'),
        t('analysis.friday'),
        t('analysis.saturday'),
        t('analysis.sunday'),
    ],
    'day': [
        t('analysis.day1'),
        t('analysis.day2'),
        t('analysis.day3'),
        t('analysis.day4'),
        t('analysis.day5'),
        t('analysis.day6'),
        t('analysis.day7'),
        t('analysis.day8'),
        t('analysis.day9'),
        t('analysis.day10'),
        t('analysis.day11'),
        t('analysis.day12'),
        t('analysis.day13'),
        t('analysis.day14'),
        t('analysis.day15'),
        t('analysis.day16'),
        t('analysis.day17'),
        t('analysis.day18'),
        t('analysis.day19'),
        t('analysis.day20'),
        t('analysis.day21'),
        t('analysis.day22'),
        t('analysis.day23'),
        t('analysis.day24'),
        t('analysis.day25'),
        t('analysis.day26'),
        t('analysis.day27'),
        t('analysis.day28'),
        t('analysis.day29'),
        t('analysis.day30'),
        t('analysis.day31'),
    ],
    'month': [
        t('analysis.january'),
        t('analysis.february'),
        t('analysis.march'),
        t('analysis.april'),
        t('analysis.may'),
        t('analysis.june'),
        t('analysis.july'),
        t('analysis.aug'),
        t('analysis.sep'),
        t('analysis.oct'),
        t('analysis.nov'),
        t('analysis.dec'),
    ],
    'quarter': [
        t('analysis.season1'),
        t('analysis.season2'),
        t('analysis.season3'),
        t('analysis.season4'),
    ]
};

/**
 * 任意事件的虚构 ID
 * @type {string}
 */
export const ARBITRARY_EVENT_ID = 'ARBITRARY_EVENT_ID';
