module.exports = {
    base:{
        confirm:'保存',
        cancel:'取消',
        determine:'确定',
        mailbox:' 请输入邮箱地址',
        forgot:'忘记密码',
        mailReg:'邮箱格式不正确',
        passwordLength:'密码长度在 6 到 12 个字符',
        passwordReg:'仅支持6-12位的数字及大小写英文字母',
        search:'搜索',
        noData:'暂无数据',
        setUp:'账户设置',
        logOut: '退出登录',
        serialNumber: '序号',
        creationTime: '创建时间',
        enableOrNot: '是否启用',
        operation: '操作',
        edit:'编辑',
        del: '删除',
        graphicTitle: '图文标题',
        graphicTypeName: '图文类型',
        delTitle: '确认删除',
        confirmDel: '删除后不可撤销!确认删除?',
        delSuccess: '删除成功',
        content: '内容',
        optSuccessful: '操作成功',
        uploadSuccess: '上传成功',
        uploadRegJPG$PNG$JPEG: '仅支持上传格式为jpg,png,jpeg的图片文件!',
        uploadRegMustLessThan5M: '该文件大小超过5M，无法上传!',
        imagesLook: '张图片,点击预览',
        opFailed: '操作失败!'
    },
    login: {
        loginTitle:'房产投资项目管理系统',
        password:'请输入登录密码',
        sign:'登录',
        emailAddress:'邮箱：',
        sendSuccess:'发送成功'
    },
    staff:{
        breadcrumb:'员工管理',
        jobNumber:'员工工号',
        staffName:'员工姓名',
        phone:'手机号',
        mailbox:'邮箱',
        position:'职位',
        states:'启用状态',
        all:'全部',
        enable:'启用',
        disable:'禁用',
        establishStaff:'创建员工账户',
        LastLogin:'最后登录时间',
        addStaff:'新增员工',
        editStaff:'编辑员工',
        addSuccess:'员工创建成功!',
        editSuccess:'员工编辑成功!',
        nameRequired:'姓名不允许为空!',
        nameLength:'长度不得超过100',
        phoneRequired:'手机号码不能为空',
        phoneReg:'请输入正确的手机号',
        positionRequired:'请选择职位',
        statesRequired:'请选择启用状态',
        name:'姓名',
        dialogTitleAdd:'新增员工',
        dialogTitleEdit:'编辑员工',
        tips:'注意:修改手机号并不会更新账户初始密码.'
    },
    account:{
        oldPassword:'旧密码',
        newPassword:'新密码',
        checkPassword:'确认新密码',
        oldPasswordReg:'请输入您的旧密码',
        newPasswordReg:'请输入您的新密码',
        checkPasswordReg:'请输入您的确认新密码',
        newPlaceholder:'请输入6~12位的字符,支持数字及大小写英文字母',
        submit:'提交',
        submitSuccess:'提交成功'
    },
    user:{
        breadcrumb:'用户管理',
        searchPlaceholder:'姓名/账户英文名/手机号/邮箱',
        serialNumber:'序号',
        chineseName:'姓名',
        englishName:'账户英文名',
        email:'邮箱',
        phone:'联系电话',
        documentTypeName:'证件类型',
        idNumber:'证件号',
        address:'通讯地址',
        registerTime:'注册时间',
        lastLoginTime:'最后登录时间',
        enableStatus:'是否启用',
        view:'查看',
        details:'用户详情',
        country:'国家',
        area:'地区',
        address1:'地址1',
        address2:'地址2',
        qualificationCertificationName:'资质认证',
        investmentExperience:'投资经验',
        enable:'启用',
        disable:'禁用',
    },
    graphic: {
        breadcrumb:'图文管理',
        states: '启用状态',
        establishGraphic:'创建图文',
        publisher: '发布者',
        coverPicture: '封面图',
        postscript: '备注',
        graphicTitleRequired: '请输入图文标题',
        graphicTypeNameRequired: '请选择图文类型',
        most5PictureMustLessThan5MClickPreview: '注意:最多上传5张,每张图片不超过5M,此处封面仅展示默认icon,点击后可查看及删除已上传图片.图片格式支持jpg,png,jpeg等.',
        most5Picture:'最多上传五张图片!'
    }
};
